/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { User } from './user';

export interface Item {
  id?: number;
  title?: string;
  description?: string;
  status?: string;
  dueDate?: string;
  user?: User;
}
