/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Item } from './item';
import type { Role } from './role';

export interface User {
  id?: number;
  username?: string;
  password?: string;
  items?: Item[];
  roles?: Role[];
}
